//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MDIBitmap.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MDIBITTYPE                  129
#define IDB_HAPPY_SUN_BM                130
#define IDR_WORKSPACE                   130
#define IDR_PROJECTTYPE                 130
#define IDB_SCRIPT_TOOL_BOX             132
#define IDR_SCRIPT_TOOLS                135
#define IDB_SCRIPT_TOOL_BASE            136
#define IDB_SCRIPT_LIFT_PHONE           137
#define IDB_SCRIPT_WAIT_RING            138
#define IDB_SCRIPT_DROP_PHONE           139
#define IDD_PLAY_FILE_PROP              139
#define IDB_SCRIPT_PROMPT_CODE          140
#define IDD_LABEL_PROP                  140
#define IDR_RIGHT_MOUSE                 140
#define IDB_SCRIPT_REC_MSG              141
#define IDD_ENTER_CODE_PROP             141
#define IDB_SCRIPT_ERASE_ALL            142
#define IDD_NO_PROP                     142
#define IDB_SCRIPT_ANS_ON               143
#define IDD_TRANS_SELECT                143
#define IDB_SCRIPT_ANS_OFF              144
#define IDD_SCRIPT_SIMULATOR            144
#define IDD_NEW_PROJECT_DLG             145
#define IDB_SCRIPT_ASK_QUESTION         146
#define IDB_SCRIPT_PLAY_FILE            147
#define IDR_ANNOUNCE_POPUP              147
#define IDB_SCRIPT_PLAY_ALL             148
#define IDR_SCRIPT_POPUP                148
#define IDD_PROJ_PROP_DLG               148
#define IDB_SCRIPT_LABEL                149
#define IDR_PHONE_BOOK_POPUP            149
#define IDB_SIMULATION_ARROW            151
#define IDC_ANNOUNCEMENT                1002
#define IDC_BUTTON1                     1003
#define IDC_BRWS_SCRIPT                 1004
#define IDC_BRWS_PHONE_BOOK             1005
#define IDC_BRWS_LOCATION               1006
#define IDC_LABEL                       1007
#define IDC_ADD_FILE                    1008
#define IDC_CODE                        1009
#define IDC_ANNOUNCEMENT_LIST           1010
#define IDC_ANNOUNCEMENT_BOX            1010
#define IDC_TRANSITION_LIST             1011
#define IDC_PLAY_FILE                   1011
#define IDC_DIAL_BUTTON                 1012
#define IDC_DIAL_BUTTON1                1012
#define IDC_EDIT1                       1013
#define IDC_CALLER_NUMBER               1013
#define IDC_BUTTON2                     1014
#define IDC_LOCATION                    1014
#define IDC_HANG_UP                     1014
#define IDC_DIAL_BUTTON2                1015
#define IDC_DIAL_BUTTON3                1016
#define IDC_DIAL_BUTTON4                1017
#define IDC_DIAL_BUTTON5                1018
#define IDC_DIAL_BUTTON6                1019
#define IDC_DIAL_BUTTON7                1020
#define IDC_DIAL_BUTTON8                1021
#define IDC_DIAL_BUTTON9                1022
#define IDC_DIAL_BUTTON10               1023
#define IDC_DIAL_BUTTON_STAR            1023
#define IDC_DIAL_BUTTON11               1024
#define IDC_DIAL_BUTTON0                1024
#define IDC_DIAL_BUTTON12               1025
#define IDC_DIAL_BUTTON_POUND           1025
#define IDC_BUTTON3                     1026
#define IDC_MAKE_CALL                   1026
#define IDC_BUTTON4                     1027
#define IDC_BUTTON5                     1028
#define IDC_STATUS                      1029
#define IDC_NEW_PROJECT_SCRIPT          1032
#define IDC_NEW_PROJECT_PHONE_BOOK      1033
#define IDC_PROJECT_NAME                1035
#define IDC_TITLE                       1036
#define IDC_PATH                        1037
#define IDC_SIMULATOR_ON                1037
#define ID_OBJECT_NEW                   32771
#define ID_OBJECT_ADDTRANSITION         32774
#define ID_OBJECT_ADD_TRANSITION        32775
#define ID_EDIT_DELETE                  32777
#define ID_SCRIPT_LIFT_PHONE            32781
#define ID_SCRIPT_DROP_PHONE            32782
#define ID_SCRIPT_WAIT_FOR_CALL         32783
#define ID_SCRIPT_PLAY                  32784
#define ID_SCRIPT_ASK_QUESTION          32785
#define ID_SCRIPT_REC_MSG               32786
#define ID_SCRIPT_ERASE_MSG             32788
#define ID_SCRIPT_ANSWER_ON             32790
#define ID_SCRIPT_ANSWER_OFF            32791
#define ID_VIEW_SCRIPT_TOOLBAR          32793
#define ID_SCRIPT_PROMPT_CODE           32795
#define ID_PROJECT_ADDTOPROJECT         32796
#define ID_PROJECT_ADDANNOUNCEMENT      32796
#define ID_PROJECT_OPENWORKSPACE        32797
#define ID_PROJECT_CLOSEWORKSPACE       32798
#define ID_PROJECT_SAVEWORKSPACE        32799
#define ID_SCRIPT_PLAY_ALL              32804
#define ID_SCRIPT_INSERT_LABEL          32806
#define ID_OBJECT_PROP                  32807
#define ID_SCRIPT_GENERATE_BAT_FILE     32808
#define ID_SCRIPT_SIMULATE_SCRIPT       32809
#define ID_CUSTOM_CANCEL                32810
#define ID_PROJECT_SELECTSCRIPT         32811
#define ID_PROJECT_SELECTPHONEBOOK      32812
#define ID_PROJECT_SELECT_SCRIPT        32813
#define ID_PROJECT_ADD_ANNOUNCEMENT     32814
#define ID_PROJECT_SELECT_PHONE_BOOK    32815
#define ID_PROJECT_EDITSCRIPT           32816
#define ID_PROJECT_OPEN_SCRIPT          32817
#define ID_PROJECT_PLAY_ANNOUNCEMENT    32818
#define ID_PROJECT_NEW_ANNOUNCEMENT     32820
#define ID_PROJECT_OPEN_ANNOUNCEMENT    32821
#define ID_PROJECT_DELETE_ANNOUNCEMENT  32822
#define ID_PROJECT_OPEN_PHONE_BOOK      32823
#define ID_PROJECT_PROPERTIES           32824
#define ID_PROJECT_SIMULATE_PROJECT     32825

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32826
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
